### ISSUE TITLE
Implement and abstract controller that implement RequestHandlerInterface

### ISSUE THREAD

**Issue by ruslanbaidan** [laminas/laminas-mvc#116]
### Feature Request
Abstract controller that will implement RequestHandlerInterface and dispatch the request to the specific restful action.

#### Summary
Extending of this controller can allow to add a specific controller to a PipeSpec list.
And therefor providing a link between Middleware PSR-15 specification and mvc controllers based application.
The feature can be useful in previously or new applications that use mvc controllers and require middleware process before a particular actions call (validate some params, add attributes etc.).

Linked also to https://github.com/laminas/laminas-psr7bridge/issues/20.
Added a draft of the idea: https://github.com/laminas/laminas-mvc/pull/117

**Comment by rieschl** [comment]
Isn't this what [laminas-mvc-middleware](https://docs.laminas.dev/laminas-mvc-middleware/) already does?

**Comment by ruslanbaidan** [comment]
> [13 hours ago](#issuecomment-1132048597)
If we add a controller that extends AbstractRestfulController to the PipeSpec [list](https://docs.laminas.dev/laminas-mvc-middleware/v2/dispatching-middleware/#pipespec-with-psr-15-service-names), there will be an error [InvalidMiddlewareException](https://github.com/laminas/laminas-mvc-middleware/blob/2.3.x/src/HandlerFromPipeSpecFactory.php#L32-L55), as it has to implement  one of RequestHandlerInterface or MiddlewareInterface.

**Comment by Xerkus** [comment]
Controllers running in pipeline behind middleware have some fundamental issues. Request/Response mutability, MvcEvent mutability and necessity to have event state to flow back up the call stack for followup events.

You can add decorator that would work for your specific application but I do not think it is something that can be supported here as  generic approach because it has to necessarily make multiple assumptions about controller implementation.

Proposed draft approach does not really make much sense since it would be better to provide straight up psr request handler if controller has to extend psr aware abstract class. Psr decorator would be better but it would have to do a lot of brittle application specific wiring.

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
